version: "3.8"

services:
  web-postgres:
    image: postgres:13
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - web-postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  web-postgres-data:
  prometheus_data:
